name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List repo root contents
      run: ls -la

    - name: Create build directory and list contents before build
      run: |
        mkdir -p build
        ls -la
        cd build
        ls -la

    - name: Build and run tests
      run: |
        cd build
        cmake ..
        make
        cd ..
        ./full-test.sh

