name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Make full-test.sh executable
      run: chmod +x ./full-test.sh

    - name: Run unit tests
      run: ./full-test.sh
